include Makefile.pre68k
SOURCES_CXX := $(filter-out $(wildcard $(FBNEO_BURN_DIR)/drv/*/*.cpp),$(SOURCES_CXX))
SOURCES_CXX += $(ATARI_DIR)/d_missile.cpp $(FBNEO_BURN_DIR)/drv/pre90s/d_millipede.cpp $(FBNEO_BURN_DIR)/drv/taito/d_arkanoid.cpp
SOURCES_CXX += $(FBNEO_CPU_DIR)/m6805_intf.cpp $(FBNEO_CPU_DIR)/m6805/m6805.cpp $(FBNEO_BURN_DEVICES_DIR)/taito_m68705.cpp
CFLAGS := $(filter-out -DNO_NEOGEO,$(CFLAGS))
CXXFLAGS := $(filter-out -DNO_NEOGEO,$(CXXFLAGS))
include Makefile.neogeo
SOURCES_C := $(sort $(SOURCES_C))
SOURCES_CXX := $(sort $(SOURCES_CXX))
